server:
  port: 7777
spring:
  application:
    name: Circuit_Breaker
    
    management:
  health:
    circuitbreakers:
      enabled: true
      
resilience4j:
  circuitbreaker:
    instances:
      MyCircuitBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10 
        failure-rate-threshold: 2
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based




