server:
  port: 8082
spring:
  application:
    name: MS_Config_Server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/tahanaushad1/MS_Config_Server
