management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
spring:
  application:
    name: MS_RestAPI
#  boot:
#    admin:
#      client:
#        url: http://localhost:1111/
  config:
    import: configserver:http://localhost:9091
